// Summarises runs/*.jsonl into results.md. Every stored model output is re-parsed offline with both grammars
// (v1 = plain lenient, v2 = close-by-lookahead), so arms run before and after the v2 change compare like for like.
import fs from 'node:fs';
import { reparse } from './reparse.mjs';

const dir = new URL('runs/', import.meta.url);
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.jsonl') && !f.includes('.repair')).sort();
const pct = (a, b) => (b ? `${((100 * a) / b).toFixed(1)}%` : '-');
const q = (xs, p) => { const s = xs.filter(Number.isFinite).sort((a, b) => a - b); return s.length ? s[Math.min(s.length - 1, Math.floor(p * (s.length - 1) + 0.5))] : NaN; };
const med = (xs) => q(xs, 0.5);

const out = ['# S2 results (generated by analyze.mjs)', '',
  'Model gpt-oss:20b on Ollama cloud, `/v1/chat/completions` streaming, temperature 0.2, prompt = DESIGN §5.7 `translate@1` draft with the title as the brief.',
  'real = 49 chunks from the 10 S3 fixtures (541 segments); adv = 5 synthetic adversarial chunks (31 segments). All outputs re-parsed offline; v2 is the proposed grammar.', ''];
const T = ['| arm | set | chunks ok | strict (v2) | lenient-fixed chunks (v2) | missing segs | merged | empty | cut chunks | re-request segs v2 (v1) | ambiguous chunks v2 (v1) | marker issues segs | html tags in output segs | untranslated segs | finish=length |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|'];
const T2 = ['| arm | set | reasoning chars med / p90 / max | completion tokens med (p90) | content share of output chars med | est. content tokens ÷ source tokens med (p90, max) | completion tokens ÷ source tokens med (p90, max) | first content s med (p90) | total s med (p90) | non-200 attempts |', '|---|---|---|---|---|---|---|---|---|---|'];
const T3 = ['| arm | chunks | escaped entities sent | chunks where all entities came back as entities | chunks where some or all were decoded to literal < > & |', '|---|---|---|---|---|'];
const fixKinds = {}; const detail = [];
for (const f of files) {
  const arm = f.replace('.jsonl', '');
  const all = fs.readFileSync(new URL(f, dir), 'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);
  for (const set of ['real', 'adv']) {
    const rows = all.filter((r) => (set === 'adv') === r.chunk.startsWith('adv#'));
    if (!rows.length) continue;
    const ok = rows.filter((r) => r.status === 200);
    const P2 = ok.map((r) => reparse(r, 'v2')), P1 = ok.map((r) => reparse(r, 'v1'));
    const segs = ok.reduce((n, r) => n + r.nSegs, 0);
    const S = (P, fn) => P.reduce((n, x) => n + fn(x), 0);
    for (const x of P2) for (const fx of x.res.fixes) { const k = `${arm}/${set}/${fx.kind}`; fixKinds[k] = (fixKinds[k] ?? 0) + 1; }
    const mk = S(P2, (x) => Object.values(x.markers).filter((v) => v.some((k) => k !== 'html')).length);
    const html = S(P2, (x) => Object.values(x.markers).filter((v) => v.includes('html')).length);
    T.push(`| ${arm} | ${set} | ${ok.length}/${rows.length} | ${P2.filter((x) => x.res.strict).length}/${ok.length} | ${P2.filter((x) => x.res.fixes.length).length} | ${S(P2, (x) => x.res.missing.length)} / ${segs} | ${S(P2, (x) => x.pl.merged.length)} | ${S(P2, (x) => x.pl.empty.length)} | ${P2.filter((x) => x.res.cut).length} | ${S(P2, (x) => x.pl.rerequest.length)} (${S(P1, (x) => x.pl.rerequest.length)}) | ${P2.filter((x) => x.pl.ambiguous).length} (${P1.filter((x) => x.pl.ambiguous).length}) | ${mk} (${pct(mk, segs)}) | ${html} | ${S(P2, (x) => x.untranslated)} | ${ok.filter((r) => r.finish === 'length').length} |`);
    // Ollama reports one completion_tokens figure (reasoning + content). Content tokens are estimated by the content
    // share of output characters; source tokens are estimated as source chars / 4.
    const share = (r) => r.contentChars / Math.max(1, r.contentChars + r.reasoningChars);
    const src = (r) => Math.max(1, r.srcChars / 4);
    const u = ok.filter((r) => r.usage);
    const mult = u.map((r) => (r.usage.completion_tokens * share(r)) / src(r)), tot = u.map((r) => r.usage.completion_tokens / src(r));
    const non200 = rows.flatMap((r) => r.attempts ?? []);
    T2.push(`| ${arm} | ${set} | ${med(ok.map((r) => r.reasoningChars))} / ${q(ok.map((r) => r.reasoningChars), 0.9)} / ${Math.max(...ok.map((r) => r.reasoningChars))} | ${med(u.map((r) => r.usage.completion_tokens))} (${q(u.map((r) => r.usage.completion_tokens), 0.9)}) | ${med(ok.map(share)).toFixed(2)} | ${med(mult).toFixed(2)} (${q(mult, 0.9).toFixed(2)}, ${Math.max(...mult).toFixed(2)}) | ${med(tot).toFixed(2)} (${q(tot, 0.9).toFixed(2)}, ${Math.max(...tot).toFixed(2)}) | ${(med(ok.map((r) => r.tContent)) / 1000).toFixed(1)} (${(q(ok.map((r) => r.tContent), 0.9) / 1000).toFixed(1)}) | ${(med(ok.map((r) => r.ms)) / 1000).toFixed(1)} (${(q(ok.map((r) => r.ms), 0.9) / 1000).toFixed(1)}) | ${non200.length}${non200.length ? ' (' + [...new Set(non200.map((a) => a.status ?? a.error))].join(', ') + ')' : ''} |`);
    ok.forEach((r, i) => {
      const x = P2[i], y = P1[i];
      if (x.res.fixes.length || x.res.missing.length || Object.keys(x.markers).length || x.res.cut || x.pl.rerequest.length || y.pl.rerequest.length)
        detail.push(`- ${arm} ${r.chunk}: v2 fixes ${JSON.stringify(x.res.fixes.map((k) => k.kind + (k.id ? ':' + k.id : '')))}; missing ${JSON.stringify(x.res.missing)}; cut ${x.res.cut ? x.res.cut.id + ` (${x.res.cut.text.length} chars)` : '-'}; re-request v2 ${JSON.stringify(x.pl.rerequest)} / v1 ${JSON.stringify(y.pl.rerequest)}; markers ${JSON.stringify(x.markers)}; finish ${r.finish}; reasoning ${r.reasoningChars} chars${r.reasoningHasSeg ? ' (mentions <seg)' : ''}`);
    });
  }
  const esc = all.filter((r) => r.status === 200 && r.escape && r.entitiesIn);
  if (esc.length) T3.push(`| ${arm} | ${esc.length} | ${esc.reduce((n, r) => n + r.entitiesIn, 0)} | ${esc.filter((r) => r.entitiesOut >= r.entitiesIn).length} | ${esc.filter((r) => r.entitiesOut < r.entitiesIn).length} |`);
}
out.push('## Parse outcomes', '', ...T, '', '## Reasoning, tokens, latency', '', ...T2, '', '## Escaped arm: do entities survive?', '', ...T3, '',
  '## Fix kinds under v2 (count)', '', ...Object.entries(fixKinds).map(([k, v]) => `- ${k}: ${v}`), '', '## Every chunk with a fix, a missing/cut segment, a marker issue or a re-request', '', ...detail, '');
fs.writeFileSync(new URL('results.md', import.meta.url), out.join('\n'));
console.log([...T, '', ...T2, '', ...T3, '', ...Object.entries(fixKinds).map(([k, v]) => `${k}: ${v}`)].join('\n'));
